export const GET_MOVIE_REQUEST = 'GET_MOVIE_REQUEST';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_ERROR = 'GET_MOVIE_ERROR';

export const GET_MOVIE_BY_ID_REQUEST = 'GET_MOVIE_BY_ID_REQUEST';
export const GET_MOVIE_BY_ID_SUCCESS = 'GET_MOVIE_BY_ID_SUCCESS';
export const GET_MOVIE_BY_ID_ERROR = 'GET_MOVIE_BY_ID_ERROR';
export const CLEAR_MOVIE_BY_ID = 'CLEAR_MOVIE_BY_ID';

export const GET_MOVIE_NEXT_PAGE_REQUEST = 'GET_MOVIE_NEXT_PAGE_REQUEST';
export const GET_MOVIE_NEXT_PAGE_SUCCESS = 'GET_MOVIE_NEXT_PAGE_SUCCESS';
export const GET_MOVIE_NEXT_PAGE_ERROR = 'GET_MOVIE_NEXT_PAGE_ERROR';

export const GET_MOVIE_AUTOCOMPLETE_REQUEST = 'GET_MOVIE_AUTOCOMPLETE_REQUEST';
export const GET_MOVIE_AUTOCOMPLETE_SUCCESS = 'GET_MOVIE_AUTOCOMPLETE_SUCCESS';
export const GET_MOVIE_AUTOCOMPLETE_ERROR = 'GET_MOVIE_AUTOCOMPLETE_ERROR';
